clean_cache: &clean_cache
    language: rust
    sudo: required
    dist: trusty
    if: type = cron
    cache:
        directories: # cargo caching from https://docs.travis-ci.com/user/caching/#rust-cargo-cache
            - $HOME/.cargo
            - $HOME/.rustup/toolchains
            - $HOME/lib
            - $HOME/include
            - $HOME/bin
    install:
    script: echo "Cleaning cargo cache ..."
        rm -rf $HOME/.cargo/registry
        rm -rf $HOME/.rustup/toolchains
        cargo clean

rust: &rust
    language: rust
    dist: trusty
    addons:
        apt:
            packages:
                - libssl-dev
                - libcurl4-openssl-dev
                - libelf-dev
                - libdw-dev
                - cmake
                - gcc
                - binutils-dev
                - libc6-dev
    cache:
        directories:
            - $HOME/.cargo
            - $HOME/.rustup/toolchains
            - $HOME/lib
            - $HOME/include
            - $HOME/bin
    before_cache:
        - du -sh $HOME/.cargo $HOME/.rustup/toolchains $HOME/lib $HOME/include $HOME/bin
        - rm -rf $HOME/.cargo/registry/src
    env:
        - RUST_BACKTRACE=1
        - RUSTFLAGS="-Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3"
        - PATH=$HOME/.local/bin:$PATH
        - LD_LIBRARY_PATH=$HOME/lib
        - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
    before_install: # versions from https://github.com/erickt/rust-zmq/blob/master/.travis.yml
        - ./ci-scripts/install-zeromq.sh
        - nvm install 10
        - nvm use 10

jobs:
    allow_failures:
        - rust: nightly
    include:
        - stage: Build and Test
          name: Build (stable)
          <<: *rust
          rust: stable
          script:
              - npm install
              - npm run build || travis_terminate 1
        - <<: *rust
          name: Build (nightly)
          rust: nightly
          script:
              - npm install
              - npm run build || travis_terminate 1
        - <<: *rust
          name: Test (stable)
          rust: stable
          script:
              - npm install
              - npm run neon-build || travis_terminate 1
              - npm run test || travis_terminate 1
        - <<: *rust
          name: Test (nightly)
          rust: nightly
          script:
              - npm install
              - npm run neon-build || travis_terminate 1
              - npm run test || travis_terminate 1
        - stage: Integration Test
          name: Integration Test
          <<: *rust
          script:
              - npm install
              - npm run build
              - ./ci-scripts/run-integration-tests.sh